### ISSUE TITLE
I reported this one through the yandex BBP now just became your research work?

### ISSUE THREAD

**Issue by peaceooout** [jollheef/libreoffice-remote-arbitrary-file-disclosure#3]
I reported this one through the yandex BBP last December and i got all email recorded and now just became an independent research work of your guys after you fix it?
https://t.co/rYqtDcxjio
https://t.co/UH5RabMQd0

**Comment by jollheef** [comment]
Yandex BBP? I don't get how libreoffice can be connected with Yandex. Can you tell in more details?

However, I does not work at Yandex.

**Comment by peaceooout** [comment]
But i see other guys that credited by this issue seems work for yandex team.And this issue is just same as the one i reported to them.


________________________________
发件人: Mikhail Klementev <notifications@github.com>
发送时间: 2018年2月13日 10:54
收件人: jollheef/libreoffice-remote-arbitrary-file-disclosure
抄送: pnigos; Author
主题: Re: [jollheef/libreoffice-remote-arbitrary-file-disclosure] I reported this one through the yandex BBP now just became your research work? (#3)


Yandex BBP? I don't get how libreoffice can be connected with Yandex. Can you tell in more details?

However, I does not work at Yandex.

―

**Comment by peaceooout** [comment]
I reported this to them cause one of their application affected by this issue.


________________________________
发件人: Mikhail Klementev <notifications@github.com>
发送时间: 2018年2月13日 10:54
收件人: jollheef/libreoffice-remote-arbitrary-file-disclosure
抄送: pnigos; Author
主题: Re: [jollheef/libreoffice-remote-arbitrary-file-disclosure] I reported this one through the yandex BBP now just became your research work? (#3)


Yandex BBP? I don't get how libreoffice can be connected with Yandex. Can you tell in more details?

However, I does not work at Yandex.

―

**Comment by jollheef** [comment]
I do not know these people. Their names are written according to the libreoffice advisory. I recently found this vulnerability and did full disclosure. 

So, what can I do for you?

**Comment by peaceooout** [comment]
Nothing here i think,i'll confirm this with them through their BBP and sorry to bother you :)



________________________________
发件人: Mikhail Klementev <notifications@github.com>
发送时间: 2018年2月13日 11:02
收件人: jollheef/libreoffice-remote-arbitrary-file-disclosure
抄送: pnigos; Author
主题: Re: [jollheef/libreoffice-remote-arbitrary-file-disclosure] I reported this one through the yandex BBP now just became your research work? (#3)


I do not know these people. Their names are written according to the libreoffice advisory. I recently found this vulnerability and did full disclosure.

So, what can I do for you?

―

**Comment by jollheef** [comment]
Ok. No problem.
